finance_questions = [
    {"id": 1, "sector": "finance", "question": "What does ROI stand for?", "options": ["Return on Investment", "Rate of Inflation", "Revenue on Income", "Return on Industry"], "answer": "Return on Investment"},
    {"id": 2, "sector": "finance", "question": "Which statement shows a company’s financial position?", "options": ["Cash Flow", "Income Statement", "Balance Sheet", "Profit & Loss"], "answer": "Balance Sheet"},
    {"id": 3, "sector": "finance", "question": "BSE in India stands for?", "options": ["Bombay Stock Exchange", "Bangalore Stock Exchange", "Bharat Share Exchange", "Business Stock Exchange"], "answer": "Bombay Stock Exchange"},
    {"id": 4, "sector": "finance", "question": "What does 'liquidity' mean in finance?", "options": ["Ability to raise debt", "Ability to convert assets into cash", "Ability to earn profits", "Ability to increase capital"], "answer": "Ability to convert assets into cash"},
    {"id": 5, "sector": "finance", "question": "Which is a short-term financial instrument?", "options": ["Treasury Bill", "Equity Share", "Debenture", "Bond"], "answer": "Treasury Bill"},
    {"id": 6, "sector": "finance", "question": "What is the full form of GST?", "options": ["Goods and Service Tax", "Gross Sale Tax", "Government Service Tax", "Global Service Tax"], "answer": "Goods and Service Tax"},
    {"id": 7, "sector": "finance", "question": "Which ratio measures a company’s profitability?", "options": ["Debt Ratio", "Liquidity Ratio", "Return on Equity", "Inventory Ratio"], "answer": "Return on Equity"},
    {"id": 8, "sector": "finance", "question": "Which organization regulates the stock market in India?", "options": ["RBI", "SEBI", "NABARD", "IRDA"], "answer": "SEBI"},
    {"id": 9, "sector": "finance", "question": "What is a company’s first public sale of shares called?", "options": ["Initial Public Offering", "Bond Issue", "Private Equity", "Venture Capital"], "answer": "Initial Public Offering"},
    {"id": 10, "sector": "finance", "question": "What does NAV stand for in mutual funds?", "options": ["Net Asset Value", "Net Annual Value", "Nominal Asset Value", "New Asset Value"], "answer": "Net Asset Value"},
    {"id": 11, "sector": "finance", "question": "Which type of account is maintained by a bank for daily transactions?", "options": ["Fixed Deposit", "Savings Account", "Current Account", "Recurring Deposit"], "answer": "Current Account"},
    {"id": 12, "sector": "finance", "question": "In accounting, assets minus liabilities is called?", "options": ["Equity", "Revenue", "Profit", "Capital"], "answer": "Equity"},
    {"id": 13, "sector": "finance", "question": "Which market deals with short-term borrowing?", "options": ["Capital Market", "Money Market", "Foreign Exchange Market", "Derivatives Market"], "answer": "Money Market"},
    {"id": 14, "sector": "finance", "question": "Who presents the Union Budget in India?", "options": ["Finance Minister", "Prime Minister", "President", "RBI Governor"], "answer": "Finance Minister"},
    {"id": 15, "sector": "finance", "question": "Which financial statement shows income and expenses?", "options": ["Cash Flow", "Balance Sheet", "Profit & Loss", "Trial Balance"], "answer": "Profit & Loss"},
    {"id": 16, "sector": "finance", "question": "Which tax is levied on income in India?", "options": ["VAT", "Income Tax", "Service Tax", "Customs Duty"], "answer": "Income Tax"},
    {"id": 17, "sector": "finance", "question": "What does ATM stand for?", "options": ["Automatic Teller Machine", "Any Time Money", "Automated Transfer Mechanism", "Automated Transaction Machine"], "answer": "Automatic Teller Machine"},
    {"id": 18, "sector": "finance", "question": "Which of these is NOT a liability?", "options": ["Loan", "Creditors", "Capital", "Outstanding Expenses"], "answer": "Capital"},
    {"id": 19, "sector": "finance", "question": "The head of RBI is called?", "options": ["Finance Secretary", "RBI Chairman", "Governor", "President"], "answer": "Governor"},
    {"id": 20, "sector": "finance", "question": "What does SIP stand for in mutual funds?", "options": ["Systematic Investment Plan", "Saving in Portfolio", "Simple Investment Process", "Standard Income Plan"], "answer": "Systematic Investment Plan"},
    {"id": 21, "sector": "finance", "question": "Which is India’s central bank?", "options": ["RBI", "SBI", "SEBI", "ICICI"], "answer": "RBI"},
    {"id": 22, "sector": "finance", "question": "Which is NOT a current asset?", "options": ["Cash", "Debtors", "Stock", "Building"], "answer": "Building"},
    {"id": 23, "sector": "finance", "question": "Which tax replaced Service Tax in India?", "options": ["GST", "Income Tax", "Wealth Tax", "Capital Gains Tax"], "answer": "GST"},
    {"id": 24, "sector": "finance", "question": "Which is a long-term source of finance?", "options": ["Overdraft", "Debentures", "Trade Credit", "Bank Loan (short-term)"], "answer": "Debentures"},
    {"id": 25, "sector": "finance", "question": "Which body issues currency notes in India?", "options": ["Finance Ministry", "SEBI", "RBI", "SBI"], "answer": "RBI"},
    {"id": 26, "sector": "finance", "question": "What is the currency of Japan?", "options": ["Yen", "Won", "Dollar", "Peso"], "answer": "Yen"},
    {"id": 27, "sector": "finance", "question": "Which of these is NOT a financial institution?", "options": ["IMF", "World Bank", "UNESCO", "NABARD"], "answer": "UNESCO"},
    {"id": 28, "sector": "finance", "question": "Which is an example of indirect tax?", "options": ["Income Tax", "Wealth Tax", "GST", "Gift Tax"], "answer": "GST"},
    {"id": 29, "sector": "finance", "question": "Which type of shares get preference in dividend?", "options": ["Equity Shares", "Preference Shares", "Bonus Shares", "Right Shares"], "answer": "Preference Shares"},
    {"id": 30, "sector": "finance", "question": "Which financial instrument is called 'Zero Coupon Bond'?", "options": ["Bond with no interest", "Bond with high risk", "Bond with variable return", "Bond with dividend"], "answer": "Bond with no interest"}
]

marketing_questions = [
    {"id": 1, "sector": "marketing", "question": "Which is NOT part of the 4Ps of marketing?", "options": ["Product", "Price", "Promotion", "Performance"], "answer": "Performance"},
    {"id": 2, "sector": "marketing", "question": "Bounce Rate in digital marketing measures?", "options": ["Pages viewed per session", "Visitors leaving without action", "Click-through rate", "Conversion ratio"], "answer": "Visitors leaving without action"},
    {"id": 3, "sector": "marketing", "question": "Which company uses the slogan 'Just Do It'?", "options": ["Puma", "Adidas", "Nike", "Reebok"], "answer": "Nike"},
    {"id": 4, "sector": "marketing", "question": "Which of these is a traditional marketing channel?", "options": ["Facebook Ads", "TV Advertising", "Google Ads", "Instagram Stories"], "answer": "TV Advertising"},
    {"id": 5, "sector": "marketing", "question": "What does SEO stand for?", "options": ["Search Engine Optimization", "Social Engagement Outreach", "Systematic Event Operation", "Search Engine Operation"], "answer": "Search Engine Optimization"},
    {"id": 6, "sector": "marketing", "question": "Market segmentation is usually based on?", "options": ["Customer needs", "Geography", "Demographics", "All of the above"], "answer": "All of the above"},
    {"id": 7, "sector": "marketing", "question": "Which stage of the Product Life Cycle has the highest competition?", "options": ["Introduction", "Growth", "Maturity", "Decline"], "answer": "Maturity"},
    {"id": 8, "sector": "marketing", "question": "Which pricing strategy is used to quickly gain market share?", "options": ["Penetration Pricing", "Premium Pricing", "Cost-Plus Pricing", "Value Pricing"], "answer": "Penetration Pricing"},
    {"id": 9, "sector": "marketing", "question": "What does CRM stand for?", "options": ["Customer Relationship Management", "Client Resource Management", "Customer Review Method", "Channel Revenue Management"], "answer": "Customer Relationship Management"},
    {"id": 10, "sector": "marketing", "question": "Which type of marketing relies on word-of-mouth?", "options": ["Viral Marketing", "Direct Marketing", "Social Media Ads", "Paid Search"], "answer": "Viral Marketing"},
    {"id": 11, "sector": "marketing", "question": "Which of these is NOT a digital marketing channel?", "options": ["Email Marketing", "Television Ads", "SEO", "Social Media"], "answer": "Television Ads"},
    {"id": 12, "sector": "marketing", "question": "In AIDA model, 'I' stands for?", "options": ["Inspire", "Interest", "Innovation", "Investment"], "answer": "Interest"},
    {"id": 13, "sector": "marketing", "question": "Which of these is an example of B2C company?", "options": ["Infosys", "TCS", "Amazon", "Accenture"], "answer": "Amazon"},
    {"id": 14, "sector": "marketing", "question": "What does USP stand for?", "options": ["Unique Selling Proposition", "Universal Sales Plan", "User Service Policy", "Unique Sales Promotion"], "answer": "Unique Selling Proposition"},
    {"id": 15, "sector": "marketing", "question": "Which social media platform is most used for professional networking?", "options": ["Facebook", "Instagram", "LinkedIn", "Twitter"], "answer": "LinkedIn"},
    {"id": 16, "sector": "marketing", "question": "Which type of research gathers numeric data?", "options": ["Qualitative Research", "Quantitative Research", "Secondary Research", "Exploratory Research"], "answer": "Quantitative Research"},
    {"id": 17, "sector": "marketing", "question": "Which is an example of Above The Line marketing?", "options": ["TV Ads", "Direct Mail", "Personal Selling", "Telemarketing"], "answer": "TV Ads"},
    {"id": 18, "sector": "marketing", "question": "The first 'P' in the 4Ps stands for?", "options": ["Product", "Price", "People", "Place"], "answer": "Product"},
    {"id": 19, "sector": "marketing", "question": "What does PPC stand for in digital ads?", "options": ["Pay Per Click", "Promotion Per Campaign", "Post Per Customer", "Paid Product Campaign"], "answer": "Pay Per Click"},
    {"id": 20, "sector": "marketing", "question": "Which metric measures conversion of leads to customers?", "options": ["Conversion Rate", "CTR", "Impression Rate", "Engagement Rate"], "answer": "Conversion Rate"},
    {"id": 21, "sector": "marketing", "question": "What is guerrilla marketing?", "options": ["Low-cost creative marketing", "Digital ads only", "Paid celebrity promotion", "Traditional TV ads"], "answer": "Low-cost creative marketing"},
    {"id": 22, "sector": "marketing", "question": "Which marketing strategy focuses on long-term relationships?", "options": ["Transactional Marketing", "Relationship Marketing", "Direct Marketing", "Outbound Marketing"], "answer": "Relationship Marketing"},
    {"id": 23, "sector": "marketing", "question": "Which company is known for 'Think Different' campaign?", "options": ["Microsoft", "Google", "Apple", "Sony"], "answer": "Apple"},
    {"id": 24, "sector": "marketing", "question": "Which is a metric for email marketing success?", "options": ["Open Rate", "Click Rate", "Bounce Rate", "All of the above"], "answer": "All of the above"},
    {"id": 25, "sector": "marketing", "question": "In 7Ps of marketing, which one is added to services?", "options": ["People", "Price", "Profit", "Place"], "answer": "People"},
    {"id": 26, "sector": "marketing", "question": "Which advertising method targets very specific audience groups?", "options": ["Mass Marketing", "Targeted Marketing", "ATL Marketing", "BTL Marketing"], "answer": "Targeted Marketing"},
    {"id": 27, "sector": "marketing", "question": "Which is a KPI for social media campaigns?", "options": ["Engagement Rate", "Employee Productivity", "Gross Profit", "Working Capital"], "answer": "Engagement Rate"},
    {"id": 28, "sector": "marketing", "question": "Which color is often associated with trust in branding?", "options": ["Red", "Blue", "Yellow", "Black"], "answer": "Blue"},
    {"id": 29, "sector": "marketing", "question": "Which is NOT a part of the AIDA model?", "options": ["Attention", "Interest", "Desire", "Action", "Profit"], "answer": "Profit"},
    {"id": 30, "sector": "marketing", "question": "Which metric shows how often people click an ad after seeing it?", "options": ["CTR", "Conversion Rate", "CPC", "ROI"], "answer": "CTR"}
]
